sudo: false
language: cpp
compiler:
  - gcc
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - export C_INCLUDE_PATH=/usr/include/$(gcc -print-multiarch)
  - export RUN_ENV=test
  - make
script:
  - make run
after_script:
  - make clean
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gcc-multilib
      - g++-multilib
      - fuse
      - libfuse-dev
